### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jacohend** [lyft/python-confidant-client#13]
Seeing as Django, Flask, and many other mainstream projects support Python 3, I was curious about why this didn't. What dependencies prevent this package from supporting Python 3?

**Comment by jacohend** [comment]
I'll try to port this to Python 3 and report back

**Comment by ryan-lane** [comment]
Thanks! I've been meaning to get to this. You also may want to checkout modernize, rather than just using 2to3: https://python-modernize.readthedocs.io/en/latest/

**Comment by ryan-lane** [comment]
Looks like someone was also working on this: https://github.com/lyft/python-confidant-client/pull/15

**Comment by jacohend** [comment]
Garrett also issued a fix for python-kmsauth that is required for this.

**Comment by ryan-lane** [comment]
Python support was added quite a bit after the last comment.
