### ISSUE TITLE
403 Forbidden error when trying to access service

### ISSUE THREAD

**Issue by jacohend** [lyft/python-confidant-client#17]
* I have auth_key `confidant` and encryption_key `confidant_at_rest`. These have the policies from the configuration guide.
* My confidant role is `systemsmanager`. It has full IAM permissions.
* I have a confidant service `prod2`. 
* All of my ec2 machines are assigned the corresponding `prod2` IAM role.
* The AWS account keys used by the ec2 machines are for a user `staging` with full admin permissions (for debugging)

When I make this request from my ec2 machines:

`confidant --url "https://our-confidant-url.com" -k alias/confidant --from prod2 --to systemsmanager --user-type service --region us-west-2 get_service --service prod2`

It fails with:

```
2017-12-08 00:34:46,032 root: ERROR API error (response code 403): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>403 Forbidden</title>
<h1>Forbidden</h1>
<p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p>

{
    "result": false
}
```

The server error says

```
ERROR:root:Failed to validate token.
ERROR:root:Failed to decrypt authentication token.
WARNING:root:Access denied for prod2. Authentication Failed.
```

Are the directions up to date?

**Comment by jacohend** [comment]
There are too many barriers to this being a production-ready solution for us. Thanks for your help, but vault is easier to configure, doesn't require us to port two different repositories to Python 3, and has correct examples.

**Comment by ryan-lane** [comment]
No worries. If vault works better for you, go for it. It's a good product.
