### ISSUE TITLE
ImportError: No module named confidant_client.cli

### ISSUE THREAD

**Issue by russmac** [lyft/python-confidant-client#3]
This seems to be an issue with my local env although I've attempted on a brand new box that only has Confidant installed also.

```
Debian 8.5
Linux fusioncore 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
```

```
(venv)[russmac@fusioncore python-confidant-client]$ confidant
Traceback (most recent call last):
  File "/home/russmac/Documents/python-confidant-client/venv/bin/confidant", line 9, in <module>
    load_entry_point('confidant-client==1.1.15', 'console_scripts', 'confidant')()
  File "/home/russmac/Documents/python-confidant-client/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/russmac/Documents/python-confidant-client/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/home/russmac/Documents/python-confidant-client/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named confidant_client.cli
```

The only way I could get it to run was to SL the path from bin. Same for formatter.

Theirs a couple of doc improvements that would be worthwhile Ill try to find time to commit, The readme for the client links to the generic doc page rather then the client page , The client page implies you only need to install confidant through pip and not clone the repo first (although it may be obvious to most)

```
(venv)[russmac@fusioncore bin]$ ln -s $PYTHONPATH
(venv)[russmac@fusioncore python-confidant-client]$ confidant
usage: confidant [-h] [--config-files CONFIG_FILES] [--profile PROFILE]
```

I also had to install these seperately

pip install "futures==3.0.2"
pip install "botocore==1.4.53"

Grepping didn't reveal them anywhere in file tree so It might not be env specific.

**Comment by ryan-lane** [comment]
Thanks for the bug report. I'm pretty sure I see the problem. I'm not including the package in the setup.py. I'll try to get a fix in soon, which will be a bump in the released version.

**Comment by ryan-lane** [comment]
Fixed in abe9bea7b5dbb6d147e2af822452091a61dfa017. I've tested this locally through a virtualenv install outside of the repo. Let me know if it's working for you and I'll close out the issue.

**Comment by ryan-lane** [comment]
(This fix is in 1.1.16 in pypi)

**Comment by billwanjohi** [comment]
I can confirm, 1.1.16 installs and runs on Python 2

**Comment by ryan-lane** [comment]
Great. Thanks!
